# Generated by Django 4.0.3 on 2022-04-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceMasterApp', '0005_alter_asset_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
