# Generated by Django 4.0.3 on 2022-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceMasterApp', '0007_alter_asset_price_alter_asset_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
