# Generated by Django 4.0.3 on 2022-04-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceMasterApp', '0008_asset_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='total',
        ),
    ]
